### PR TITLE
Separate client vs server caps

### LINKED ISSUE #498: `@time=` message tag on `AUTHENTICATE` message despite not negotiating the `server-time` capability
Someone reported the following issue with ChatZilla on #ircv3:

```
[21:27:06]   [CAP]   ACK sasl
[21:27:07]   [@TIME=2026-02-18T20:27:06.592Z]        +
```

ChatZilla does not implement the `server-time` (or `message-tags`) specification, this looks like the server sent a line starting with `@time` which ChatZilla parsed as a command. I'm guessing `@time=2026-02-18T20:27:06.592Z :server AUTHENTICATE +`.

They use ChatZilla 0.9.88 with no plugin that uses `CAP REQ`, except https://libera.chat/static/files/cz_sasl-0.6.3.js . ChatZilla itself does not implement `CAP REQ` either.

So this looks like a bug in Solanum, but I am not able to reproduce it and neither are they.

### PR DESCRIPTION
**Pull request by skizzerz**
Instead of overloading the same field in a LocalUser, have separate fields for client caps vs server caps. While only one of these will ever be nonzero, it reduces error by making it explicit which set of caps is being checked. IsCapable and friends have been split as well, to IsClientCapable and IsServerCapable. Finally, both fields have been updated to uint64_t (server caps were approaching the current limit) and all APIs that reference caps updated to uint64_t as well (no more signed/unsigned mismatches).

Fixes #498

### CODE REVIEW

File: ircd/send.c [hunk 1]
```diff
@@ -40,8 +40,7 @@
 #include "monitor.h"
 #include "msgbuf.h"
 
-#define CLIENT_CAP_MASK(x)	(MyClient((x)) ? (x)->localClient->caps : \
-		((x)->from == &me || ((x)->from && (x)->from->localClient->caps & CAP_STAG)) ? (unsigned)-1 : 0)
+#define CLIENT_CAP_MASK(x)	((x)->from->localClient->client_caps | (((x)->from->localClient->server_caps & CAP_STAG) ? (uint64_t)-1 : 0))
```
Comment (dwfreed) [inline ircd/send.c]:
```suggestion
#define CLIENT_CAP_MASK(x)	((x)->from->localClient->client_caps | (((x)->from->localClient->server_caps & CAP_STAG) ? UINT64_MAX : 0))
```

I think this makes it more obvious what is meant

File: include/s_serv.h [hunk 2]
```diff
@@ -103,9 +103,12 @@ extern unsigned int CAP_STAG;			/* supports s2s tags and TAGMSG */
...
  */
-#define IsCapable(x, cap)       (((x)->localClient->caps & (cap)) == cap)
-#define NotCapable(x, cap)	(((x)->localClient->caps & (cap)) == 0)
-#define ClearCap(x, cap)        ((x)->localClient->caps &= ~(cap))
+#define IsClientCapable(x, cap)       (((x)->localClient->client_caps & (cap)) == cap)
+#define NotClientCapable(x, cap)	(((x)->localClient->client_caps & (cap)) == 0)
+#define ClearClientCap(x, cap)        ((x)->localClient->client_caps &= ~(cap))
+#define IsServerCapable(x, cap)       (((x)->localClient->server_caps & (cap)) == cap)
+#define NotServerCapable(x, cap)	(((x)->localClient->server_caps & (cap)) == 0)
+#define ClearServerCap(x, cap)        ((x)->localClient->server_caps &= ~(cap))
```
Comment (dwfreed) [inline include/s_serv.h]:
```suggestion
#define IsClientCapable(x, cap)         (((x)->localClient->client_caps & (cap)) == cap)
#define NotClientCapable(x, cap)        (((x)->localClient->client_caps & (cap)) == 0)
#define SetClientCap(x, cap)            ((x)->localClient->client_caps |= (cap))
#define ClearClientCap(x, cap)          ((x)->localClient->client_caps &= ~(cap))
#define IsServerCapable(x, cap)         (((x)->localClient->server_caps & (cap)) == cap)
#define NotServerCapable(x, cap)        (((x)->localClient->server_caps & (cap)) == 0)
#define SetServerCap(x, cap)            ((x)->localClient->server_caps |= (cap))
#define ClearServerCap(x, cap)          ((x)->localClient->server_caps &= ~(cap))
```

Since we're changing this anyway, might as well add a set operation too; then later if for some reason we need to make them less trivial, it's a lot easier to do.  Also I made them all line up correctly.

File: include/s_serv.h
Comment (aaronmdjones) [inline include/s_serv.h]: These should all be `uint64_t` now (likewise in `s_serv.c`) since these variables are assigned to from `capability_put()` which now returns that type.

File: tests/sasl_abort1.c [hunk 3]
```diff
@@ -52,7 +52,7 @@ static void common_sasl_test(bool aborted)
 	strcpy(server->id, TEST_SERVER_ID);
 	strcpy(remote->id, TEST_REMOTE_ID);
 	add_to_id_hash(remote->id, remote);
-	server->localClient->caps = CAP_ENCAP | CAP_TS6;
+	server->localClient->server_caps = CAP_ENCAP | CAP_TS6;
```
Comment (aaronmdjones) [inline tests/sasl_abort1.c]:
```C
SetServerCap(server, CAP_ENCAP | CAP_TS6);
```

File: modules/m_capab.c [hunk 4]
```diff
@@ -101,12 +101,12 @@ me_gcap(struct MsgBuf *msgbuf_p, struct Client *client_p, struct Client *source_
...
-		source_p->serv->caps = 0;
+		source_p->serv->server_caps = 0;
 		rb_free(source_p->serv->fullcaps);
 	}
 
 	source_p->serv->fullcaps = rb_strdup(parv[1]);
 
 	for (s = rb_strtok_r(t, " ", &p); s; s = rb_strtok_r(NULL, " ", &p))
-		source_p->serv->caps |= capability_get(serv_capindex, s, NULL);
+		SetServerCap(source_p, capability_get(serv_capindex, s, NULL));
```
Comment (aaronmdjones) [inline modules/m_capab.c]: This is not equivalent; the macro modifies the `server_caps` field in `localClient` instead.

**Review by aaronmdjones — APPROVED** [review]
